### ISSUE TITLE
Traffic Pattern Dependencies

### ISSUE THREAD

**Issue by snkas** [behnazak/Vigil-007SourceCode#1]
Dear Arzani et al.,

Your paper in NSDI was quite enjoyable to read, and the system proposal I find interesting. I have a question regarding line 11 of Algorithm 1: what traffic pattern assumptions does it make? I cannot seem to find it (or the Algorithm 1 itself) in the code. In the text is stated:

> Namely, we iteratively pick the most voted link l_max and estimate the portion of votes obtained by all other links due to failures on l_max. This estimate is obtained for each link k by (i) assuming all flows having retransmissions and going through l_max had drops due to l_max and (ii) finding what fraction of these flows go through k by assuming ECMP distributes flows uniformly at random.

In particular, P is set as the set of all possible paths, and if a link shares at least one path with l_max, its score is "adjusted". Is this adjustment done by making use of the knowledge what flows were active on which path, or done obliviously by calculating the ECMP spreading under the assumption of an all-to-all traffic matrix?

**Comment by behnazak** [comment]
Hi Simon,

Basically, the number of votes a link gets (l_max for example) shows the
number of connections that went through that link and that had packet drops
(remember votes are just the number of flows that had dropped packets
divided by the path length). What we did for the work was to assume a
uniform distribution of flows across ToRs (or hosts) and used this
assumption when backtracking . What this means is that, by using this
assumption, if you are on a T_1 link you can calculate what fraction of the
flows would go through a T_2 link and which fraction would go down to
another ToR. (we ignored T_3 for this work). Note that you get less and
less contribution to the votes on a link as you move away from it.

Another approach which is equally valid (however requires you to keep track
of all tracerouted paths) would be to take advantage of the fact that you
know the path of all flows that contributed to the votes gotten by l_max,
you can go back and set the votes of the flows that went through that link
to 0 for all other links that they went through and re-compute the votes.
This is more computationally expensive, but at the same time is also more
accurate as it removes the assumption that flows are distributed uniformly
at random across ToRs.

Hope this helps,
